### ISSUE TITLE
Update search date to include calendar or autoformatting

### ISSUE THREAD

**Issue by christian-franklin** [FlyTrackers/FlyTrackers#32]
When searching for flights I want to be able to put the date in as MM-DD-YYYY but the field requires YYYY-MM-DD. The field should automatically convert to correct format, or provide some kind of calendar pop-up that allows me to select the date.

**Comment by GPropersi** [comment]
Also include a list of airlines as a dropdown menu so user does not need to type in an airline.

**Comment by GPropersi** [comment]
List of airlines can be lengthy and I found some free options online. Will break that off into a separate issue -> we can make a search bar that uses the preloaded airlines.
